### ISSUE TITLE
Telemetry - Prometheus & Grafana charts reorganization

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astronomer#106]
https://github.com/astronomerio/helm.astronomer.io/compare/telemetry-graf-prom

https://github.com/astronomerio/helm.astronomer.io/compare/v0.3.0...telemetry-graf-prom

**Comment by schnie** [comment]
@tedmiston have you dug into this one yet? This should probably be one of the first things we knock out for this initiative.

**Comment by tedmiston** [comment]
I started the Telemetry epic from the front end client and back end server sides first thinking I'd meet them in the middle and then do this one and the install flag.  I'll DM you so we can discuss more in Slack what you have in mind.

**Comment by schnie** [comment]
We should hold off on back end until we get this straightened out since it affects the actual source of the data, and to meet our short term deliverables.

We'll need to split Prometheus and Grafana into their own top-level charts under our umbrella chart that should be enabled by default in the `requirements.yaml`. Once it's split out and living at the "platform level", we'll need to adjust the Prometheus config file to scrape all running airflow installations, rather than an individual release, like it's doing now. We _may_ need to make some adjustments to the Grafana charts as well to be more useful at the platform level.

**Comment by tedmiston** [comment]
Cool - I'm get started on that today.

I think I need a bit more context on the requirements you have in mind to get on the same page with this one.

I started with the backend, thinking that the backend receives an array of JSON blobs of event data from Prometheus, so it would be agnostic to Helm chart changes, and that Redshift loading is one of the most important parts of the deliverable.

When the Prometheus and Grafana charts are rearranged, my working thought has been that the shape of the payload to the backend doesn't change.  Maybe there's some context I'm missing here around the changes required.

I just sent you a DM hoping to get some time on your calendar, hopefully a hangout today/tomorrow/whenever you're available next.

**Comment by schnie** [comment]
Additional context from Slack convo: 

I think we just need to split out Grafana and Prometheus into their own top level charts then rework the Prometheus config (https://github.com/astronomerio/helm.astronomer.io/blob/master/charts/airflow/templates/prometheus/prometheus-configmap.yaml#L20-L86) to pull metrics from any number of Airflow installations, since we can now deploy multiple Airflow instances. Then we should probably rework the Grafana dashboards to work better with multiple Airflow instances (https://github.com/astronomerio/astronomer/tree/master/docker/vendor/grafana/include).

**Comment by tedmiston** [comment]
Greg and I got caught past a few pain points with this yesterday and moved it very close to the finish line (from 50% to 75%).  There's still a bit of work left to polish this one but it's going well.

**Comment by tedmiston** [comment]
I think we are pretty much done with this one as of today — the chart reorg is good to go.  Still working on resolving the dynamic Prometheus scraping on multiple Airflows but I'm considering that separate from this issue specifically, and I think it's close as well.

**Comment by tedmiston** [comment]
done
