### ISSUE TITLE
Distinguish Open From EE

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer#44]
After a conversation with a customer - we need to be distinguishing Open from EE. Ideas around this are 

- Add warning to docs to highlight that Open is meant for testing and viewing of EE internals, not for dev or production workflows. For this they should be pointed to the Astronomer EE CLI.

- change `airflow-enterprise` example to `airflow-ee-bundle` in order to remove the impression that the example is anywhere near feature parody to an enterprise install.

This is slightly inline with #39

**Comment by andscoop** [comment]
This doc update should also include links into enterprise docs wherever it makes sense. We want the customer to kick-the-tires and move onto enterprise demoing ASAP.

**Comment by tedmiston** [comment]
Feel free to push forward the discussion on https://github.com/astronomerio/astronomer/pull/39 since we're already talking about it and I've done some renaming there.  I think the second half of this can fall into that branch if you want to pop a comment or commit on my `airflow-examples-docs ` branch.

**Comment by andscoop** [comment]
I already opened #45 . I left any name changes of examples out of that PR. Will let that be handled in PR #39

**Comment by andscoop** [comment]
This was closed with the merging of #45
